// projects.ts
export const projects = [
  {
    id: 1,
    title: "Grand Lotus Hotel",
    company: "My project",
    description:
      "Grand Lotus Hotel is a responsive full-stack website for hotel room booking with personal accounts for clients and administrators, as well as an admin panel.",
    role: "Full Stack developer (React,Express)",
    technologies: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "CSS modules",
      "Node.js",
      "Express (EJX)",
      "MongoDB",
      "React Context",
      "React Router",
      "Docker",
    ],
    liveLink: "http://194.87.76.241:2050/",
    githubLink: "https://github.com/nikum-st/hotel",
    imageUrl: "/img/Hotel/1.png",
    images: [
      "/img/Hotel/1.png",
      "/img/Hotel/2.png",
      "/img/Hotel/3.png",
      "/img/Hotel/4.png",
      "/img/Hotel/5.png",
      "/img/Hotel/6.png",
      "/img/Hotel/7.png",
      "/img/Hotel/8.png",
      "/img/Hotel/9.png",
      "/img/Hotel/10.png",
      "/img/Hotel/11.png",
    ],
  },
  {
    id: 3,
    title: "AAG Akzent — Real Estate Developer",
    company: "Nimax",
    description:
      "Landing page of the Akzent residential complex of the AAG holding.Corporate website for a premium-class real estate developer. Focused on clean UI, responsive design, and smooth navigation for showcasing luxury housing projects.",
    role: "Frontend Developer",
    technologies: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "Vite",
      "Framer Motion",
    ],
    imageUrl: "/img/Akzent/home.png",
    liveLink: "https://akzent.aag.company/",
    images: [
      "/img/Akzent/home.png",
      "/img/Akzent/1.png",
      "/img/Akzent/2.png",
      "/img/Akzent/3.png",
    ],
  },
  {
    id: 2,
    title: "Developer Blog",
    company: "My project",
    description:
      "Developer Blog is a single-page application (SPA) built using React, Redux, Express and MongoDB. The project demonstrates a modern approach to developing full-stack applications and serves as a great example for learning best practices.",
    role: "Full Stack Developer",
    technologies: [
      "React",
      "JavaScript",
      "Redux",
      "Styled Components",
      "Node.js",
      "Express",
      "i18n",
      "Docker",
    ],
    liveLink: "http://194.87.76.241:2000/",
    githubLink: "https://github.com/Nikum-st/blog.git",
    imageUrl: "/img/Blog/1.png",
    images: [
      "/img/Blog/1.png",
      "/img/Blog/2.png",
      "/img/Blog/3.png",
      "/img/Blog/4.png",
      "/img/Blog/5.png",
      "/img/Blog/6.png",
    ],
  },

  {
    id: 4,
    title: "Letovo School",
    company: "Nimax",
    description:
      "Letovo School in digital is a system of websites: the main website of the school, an online platform for classes and testing in school subjects, personal accounts of applicants, students, employees, parents. It was necessary to think through the user's path in the interfaces of the site and personal account at each stage, make the admission process clear and simplify the presentation of important information for promotion along the track. And also to rework the general structure of the site and key pages",
    role: "Full-stack developer (with focus on frontend team)",
    technologies: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "i18next",
      "SASS/SCSS",
      "REST API",
      "Next.js",
      "MongoDB",
    ],
    imageUrl: "/img/Letovo/1.png",
    liveLink: "https://en.letovo.ru/",
    images: [
      "/img/Letovo/1.png",
      "/img/Letovo/2.png",
      "/img/Letovo/3.png",
      "/img/Letovo/4.png",
      "/img/Letovo/5.png",
    ],
  },
  {
    id: 5,
    title: "Other",
    description:
      "I continuously grow as a developer and share my side projects on GitHub – from experimental mini-apps and to a Todo app with EJS backend, a calculator, and a Tic-Tac-Toe game in React. This portfolio website itself is also built by me. I regularly share side projects on GitHub and write my thoughts on frontend and IT on LinkedIn — feel free to follow.",
    imageUrl: "/img/12.png",
    githubLink: "https://github.com/Nikum-st",
    liveLink: "https://www.linkedin.com/in/nikita-umanskii-dev/",
    role: "Frontend Developer (focus Full Stack)",
    technologies: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "CSS modules",
      "Node.js",
      "Express (EJX)",
      "MongoDB",
      "React Context",
      "React Router",
      "Docker",
    ],
  },
];
